server:
#  port: 8106  #测试
  port: 8102  #正式

spring:
  application:
      name: pdp
  datasource:
    druid:
#      url: jdbc:mysql://192.168.145.241:3306/PDP?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#      username: root
#      password: admin123password456
      url: jdbc:mysql://192.168.145.241:3306/sltest?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: admin123password456
#      url: jdbc:mysql://127.0.0.1:3306/sltest?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#      username: root
#      password: unicom
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
#  thymeleaf:
#      cache: false
#      mode: HTML5
#      encoding: UTF-8
#      content-type: text/html
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
        
mybatis:
    mapper-locations: classpath:mapper/*.xml

#设置静态资源路径，多个以逗号分隔
spring.resources.static-locations: classpath:static/,file:static/


